/**
 * Nahkya Silk Atelier — Complete Swatch System
 * 12 categories × 30 swatches = 360 colours
 * Extracted from nahkya_30_flat_swatches_per_category.pdf
 *
 * Status key:
 *   - Caution:  Light tints, may require print testing
 *   - Approved: Print-tested and production-ready
 *   - Core:     Signature brand colours
 *   - Premium:  Special / metallic finishes
 */

export type SwatchStatus = "Caution" | "Approved" | "Core" | "Premium";

export interface NahkyaSwatch {
  id: string;
  name: string;
  hex: string;
  status: SwatchStatus;
}

export interface NahkyaSwatchCategory {
  id: string;
  name: string;
  description: string;
  swatches: NahkyaSwatch[];
}

/* ────────────────────────────────────────────────────────────────────────── */

export const NAHKYA_SWATCH_CATEGORIES: NahkyaSwatchCategory[] = [
  {
    id: "reds-burgundy",
    name: "Reds & Burgundy",
    description: "Rose-red, ruby, wine, maroon, oxblood, deep burgundy.",
    swatches: [
      { id: "reds-burgundy-petal-red", name: "Petal Red", hex: "#EFE1E3", status: "Caution" },
      { id: "reds-burgundy-tea-rose-red", name: "Tea Rose Red", hex: "#EAD8DA", status: "Caution" },
      { id: "reds-burgundy-blushed-ruby", name: "Blushed Ruby", hex: "#E6CED1", status: "Caution" },
      { id: "reds-burgundy-soft-garnet", name: "Soft Garnet", hex: "#E2C5C8", status: "Approved" },
      { id: "reds-burgundy-rose-rouge", name: "Rose Rouge", hex: "#DFBBBE", status: "Approved" },
      { id: "reds-burgundy-muted-cranberry", name: "Muted Cranberry", hex: "#DBB0B5", status: "Approved" },
      { id: "reds-burgundy-ruby-veil", name: "Ruby Veil", hex: "#D8A6AB", status: "Approved" },
      { id: "reds-burgundy-classic-red", name: "Classic Red", hex: "#D59BA1", status: "Approved" },
      { id: "reds-burgundy-velvet-rouge", name: "Velvet Rouge", hex: "#D2909C", status: "Core" },
      { id: "reds-burgundy-raspberry-wine", name: "Raspberry Wine", hex: "#CF8593", status: "Approved" },
      { id: "reds-burgundy-cranberry-silk", name: "Cranberry Silk", hex: "#CD7A89", status: "Approved" },
      { id: "reds-burgundy-mulberry-red", name: "Mulberry Red", hex: "#CB6E7E", status: "Approved" },
      { id: "reds-burgundy-garnet-rosewood", name: "Garnet Rosewood", hex: "#C96374", status: "Approved" },
      { id: "reds-burgundy-wine-bloom", name: "Wine Bloom", hex: "#C7576A", status: "Approved" },
      { id: "reds-burgundy-claret", name: "Claret", hex: "#C64A5F", status: "Approved" },
      { id: "reds-burgundy-velvet-wine", name: "Velvet Wine", hex: "#C43E5F", status: "Core" },
      { id: "reds-burgundy-maroon-silk", name: "Maroon Silk", hex: "#BE3758", status: "Approved" },
      { id: "reds-burgundy-deep-ruby", name: "Deep Ruby", hex: "#B53252", status: "Approved" },
      { id: "reds-burgundy-burgundy", name: "Burgundy", hex: "#AC2D4C", status: "Approved" },
      { id: "reds-burgundy-dark-garnet", name: "Dark Garnet", hex: "#A32946", status: "Approved" },
      { id: "reds-burgundy-oxblood", name: "Oxblood", hex: "#992440", status: "Approved" },
      { id: "reds-burgundy-black-cherry", name: "Black Cherry", hex: "#90203B", status: "Approved" },
      { id: "reds-burgundy-deep-burgundy", name: "Deep Burgundy", hex: "#861D3E", status: "Approved" },
      { id: "reds-burgundy-merlot", name: "Merlot", hex: "#7C1938", status: "Approved" },
      { id: "reds-burgundy-dried-rosewood", name: "Dried Rosewood", hex: "#711632", status: "Core" },
      { id: "reds-burgundy-damson-wine", name: "Damson Wine", hex: "#67122C", status: "Approved" },
      { id: "reds-burgundy-aged-claret", name: "Aged Claret", hex: "#5C0F27", status: "Approved" },
      { id: "reds-burgundy-midnight-wine", name: "Midnight Wine", hex: "#510D22", status: "Approved" },
      { id: "reds-burgundy-almost-burgundy", name: "Almost Burgundy", hex: "#460A1C", status: "Caution" },
      { id: "reds-burgundy-black", name: "Black", hex: "#3A0817", status: "Caution" },
    ],
  },
  {
    id: "rose-blush",
    name: "Rose & Blush",
    description: "Blush, powder rose, peony, mauve pink, dusty rose.",
    swatches: [
      { id: "rose-blush-porcelain-blush", name: "Porcelain Blush", hex: "#F2EEED", status: "Caution" },
      { id: "rose-blush-bare-rose", name: "Bare Rose", hex: "#EEE7E6", status: "Caution" },
      { id: "rose-blush-powder-blush", name: "Powder Blush", hex: "#E9E0DE", status: "Caution" },
      { id: "rose-blush-silk-petal", name: "Silk Petal", hex: "#E5D8D7", status: "Approved" },
      { id: "rose-blush-blush-silk", name: "Blush Silk", hex: "#E1D1CF", status: "Approved" },
      { id: "rose-blush-peony-milk", name: "Peony Milk", hex: "#DDCAC8", status: "Approved" },
      { id: "rose-blush-rose-mist", name: "Rose Mist", hex: "#D9C3C0", status: "Approved" },
      { id: "rose-blush-antique-pink", name: "Antique Pink", hex: "#D5BBB8", status: "Approved" },
      { id: "rose-blush-tea-rose", name: "Tea Rose", hex: "#D2B0B3", status: "Core" },
      { id: "rose-blush-soft-peony", name: "Soft Peony", hex: "#CEA7AB", status: "Approved" },
      { id: "rose-blush-dusty-pink", name: "Dusty Pink", hex: "#CB9FA3", status: "Approved" },
      { id: "rose-blush-rose-beige", name: "Rose Beige", hex: "#C8969B", status: "Approved" },
      { id: "rose-blush-muted-rose", name: "Muted Rose", hex: "#C48E92", status: "Approved" },
      { id: "rose-blush-petal-mauve", name: "Petal Mauve", hex: "#C2858A", status: "Approved" },
      { id: "rose-blush-peony-rose", name: "Peony Rose", hex: "#BF7C81", status: "Approved" },
      { id: "rose-blush-dusty-rose", name: "Dusty Rose", hex: "#BC7385", status: "Core" },
      { id: "rose-blush-mauve-rose", name: "Mauve Rose", hex: "#BA697D", status: "Approved" },
      { id: "rose-blush-old-rose", name: "Old Rose", hex: "#B76075", status: "Approved" },
      { id: "rose-blush-rose-clay", name: "Rose Clay", hex: "#B5566D", status: "Approved" },
      { id: "rose-blush-smoked-pink", name: "Smoked Pink", hex: "#B34D65", status: "Approved" },
      { id: "rose-blush-deep-blush", name: "Deep Blush", hex: "#AC475F", status: "Approved" },
      { id: "rose-blush-victorian-rose", name: "Victorian Rose", hex: "#A5435A", status: "Approved" },
      { id: "rose-blush-muted-fuchsia", name: "Muted Fuchsia", hex: "#9E3E64", status: "Approved" },
      { id: "rose-blush-berry-rose", name: "Berry Rose", hex: "#97395F", status: "Approved" },
      { id: "rose-blush-plum-rose", name: "Plum Rose", hex: "#903559", status: "Core" },
      { id: "rose-blush-deep-mauve", name: "Deep Mauve", hex: "#883153", status: "Approved" },
      { id: "rose-blush-bruised-rose", name: "Bruised Rose", hex: "#802D4D", status: "Approved" },
      { id: "rose-blush-dark-rosewood", name: "Dark Rosewood", hex: "#792948", status: "Approved" },
      { id: "rose-blush-mauve-wine", name: "Mauve Wine", hex: "#712542", status: "Caution" },
      { id: "rose-blush-noir-rose", name: "Noir Rose", hex: "#69213C", status: "Caution" },
    ],
  },
  {
    id: "coral-terracotta",
    name: "Coral & Terracotta",
    description: "Peach, apricot, coral, clay, copper, terracotta.",
    swatches: [
      { id: "coral-terracotta-peach-milk", name: "Peach Milk", hex: "#F2ECE8", status: "Caution" },
      { id: "coral-terracotta-soft-apricot", name: "Soft Apricot", hex: "#EEE6E0", status: "Caution" },
      { id: "coral-terracotta-apricot-silk", name: "Apricot Silk", hex: "#EAE0D8", status: "Caution" },
      { id: "coral-terracotta-peach-beige", name: "Peach Beige", hex: "#E6D9CF", status: "Approved" },
      { id: "coral-terracotta-warm-peach", name: "Warm Peach", hex: "#E3D3C6", status: "Approved" },
      { id: "coral-terracotta-sunkiss-peach", name: "Sunkiss Peach", hex: "#DFCDBE", status: "Approved" },
      { id: "coral-terracotta-coral-blush", name: "Coral Blush", hex: "#DCC6B5", status: "Approved" },
      { id: "coral-terracotta-soft-coral", name: "Soft Coral", hex: "#D9C0AB", status: "Approved" },
      { id: "coral-terracotta-clay-peach", name: "Clay Peach", hex: "#D6B4A2", status: "Core" },
      { id: "coral-terracotta-apricot-clay", name: "Apricot Clay", hex: "#D3AD99", status: "Approved" },
      { id: "coral-terracotta-sandalwood", name: "Sandalwood", hex: "#D0A68F", status: "Approved" },
      { id: "coral-terracotta-muted-coral", name: "Muted Coral", hex: "#CE9F85", status: "Approved" },
      { id: "coral-terracotta-burnt-coral", name: "Burnt Coral", hex: "#CB987B", status: "Approved" },
      { id: "coral-terracotta-coral-clay", name: "Coral Clay", hex: "#C99171", status: "Approved" },
      { id: "coral-terracotta-terracotta-blush", name: "Terracotta Blush", hex: "#C78A67", status: "Approved" },
      { id: "coral-terracotta-terracotta", name: "Terracotta", hex: "#C5785C", status: "Core" },
      { id: "coral-terracotta-copper-clay", name: "Copper Clay", hex: "#C47152", status: "Approved" },
      { id: "coral-terracotta-persimmon", name: "Persimmon", hex: "#C26947", status: "Approved" },
      { id: "coral-terracotta-cinnamon", name: "Cinnamon", hex: "#BF613D", status: "Approved" },
      { id: "coral-terracotta-coral-rust", name: "Coral Rust", hex: "#B85C39", status: "Approved" },
      { id: "coral-terracotta-peach-burnt", name: "Peach Burnt", hex: "#B05734", status: "Approved" },
      { id: "coral-terracotta-apricot-clay-dark", name: "Apricot Clay Dark", hex: "#A85230", status: "Approved" },
      { id: "coral-terracotta-warm-rust", name: "Warm Rust", hex: "#A0452C", status: "Approved" },
      { id: "coral-terracotta-copper-rose", name: "Copper Rose", hex: "#974028", status: "Approved" },
      { id: "coral-terracotta-earth-coral", name: "Earth Coral", hex: "#8F3C24", status: "Core" },
      { id: "coral-terracotta-red-clay", name: "Red Clay", hex: "#863721", status: "Approved" },
      { id: "coral-terracotta-spiced-terracotta", name: "Spiced Terracotta", hex: "#7D331D", status: "Approved" },
      { id: "coral-terracotta-deep-copper", name: "Deep Copper", hex: "#742F1A", status: "Approved" },
      { id: "coral-terracotta-burnt-sienna", name: "Burnt Sienna", hex: "#6B2A17", status: "Caution" },
      { id: "coral-terracotta-dark-terracotta", name: "Dark Terracotta", hex: "#612614", status: "Caution" },
    ],
  },
  {
    id: "gold-ochre",
    name: "Gold & Ochre",
    description: "Pale gold, champagne, honey, mustard, ochre, antique gold.",
    swatches: [
      { id: "gold-ochre-ivory-gold", name: "Ivory Gold", hex: "#F4F2EC", status: "Caution" },
      { id: "gold-ochre-pale-champagne", name: "Pale Champagne", hex: "#F0EDE4", status: "Caution" },
      { id: "gold-ochre-champagne-silk", name: "Champagne Silk", hex: "#ECE8DC", status: "Caution" },
      { id: "gold-ochre-soft-wheat", name: "Soft Wheat", hex: "#E8E3D3", status: "Approved" },
      { id: "gold-ochre-pale-marigold", name: "Pale Marigold", hex: "#E4DECB", status: "Approved" },
      { id: "gold-ochre-vanilla-gold", name: "Vanilla Gold", hex: "#E1DAC2", status: "Approved" },
      { id: "gold-ochre-warm-straw", name: "Warm Straw", hex: "#DDD5B9", status: "Approved" },
      { id: "gold-ochre-light-ochre", name: "Light Ochre", hex: "#DAD1B0", status: "Approved" },
      { id: "gold-ochre-honey-cream", name: "Honey Cream", hex: "#D7CAA7", status: "Core" },
      { id: "gold-ochre-wheat-gold", name: "Wheat Gold", hex: "#D4C59E", status: "Approved" },
      { id: "gold-ochre-champagne-gold", name: "Champagne Gold", hex: "#D2C194", status: "Approved" },
      { id: "gold-ochre-soft-ochre", name: "Soft Ochre", hex: "#CFBD8A", status: "Approved" },
      { id: "gold-ochre-marigold-dust", name: "Marigold Dust", hex: "#CDB881", status: "Approved" },
      { id: "gold-ochre-honey-silk", name: "Honey Silk", hex: "#CBB477", status: "Approved" },
      { id: "gold-ochre-muted-mustard", name: "Muted Mustard", hex: "#C9B06C", status: "Approved" },
      { id: "gold-ochre-antique-gold", name: "Antique Gold", hex: "#C8A662", status: "Core" },
      { id: "gold-ochre-brass-gold", name: "Brass Gold", hex: "#C6A157", status: "Approved" },
      { id: "gold-ochre-old-gold", name: "Old Gold", hex: "#C59D4D", status: "Approved" },
      { id: "gold-ochre-golden-ochre", name: "Golden Ochre", hex: "#C39942", status: "Approved" },
      { id: "gold-ochre-saffron-brown", name: "Saffron Brown", hex: "#BF943A", status: "Approved" },
      { id: "gold-ochre-bronze-ochre", name: "Bronze Ochre", hex: "#B78E35", status: "Approved" },
      { id: "gold-ochre-burnished-gold", name: "Burnished Gold", hex: "#B08731", status: "Approved" },
      { id: "gold-ochre-caramel-gold", name: "Caramel Gold", hex: "#A8792D", status: "Approved" },
      { id: "gold-ochre-deep-mustard", name: "Deep Mustard", hex: "#A07229", status: "Approved" },
      { id: "gold-ochre-aged-brass", name: "Aged Brass", hex: "#976C25", status: "Core" },
      { id: "gold-ochre-dark-ochre", name: "Dark Ochre", hex: "#8F6621", status: "Approved" },
      { id: "gold-ochre-antique-bronze", name: "Antique Bronze", hex: "#865F1E", status: "Approved" },
      { id: "gold-ochre-umber-gold", name: "Umber Gold", hex: "#7D591A", status: "Approved" },
      { id: "gold-ochre-shadow-gold", name: "Shadow Gold", hex: "#745217", status: "Caution" },
      { id: "gold-ochre-deep-brass", name: "Deep Brass", hex: "#6B4B14", status: "Caution" },
    ],
  },
  {
    id: "green-botanical",
    name: "Green & Botanical",
    description: "Mint, sage, celadon, olive, moss, emerald, pine.",
    swatches: [
      { id: "green-botanical-mint-cream", name: "Mint Cream", hex: "#EAF0EC", status: "Caution" },
      { id: "green-botanical-pale-celadon", name: "Pale Celadon", hex: "#E1EBE5", status: "Caution" },
      { id: "green-botanical-tea-green", name: "Tea Green", hex: "#D9E6DE", status: "Caution" },
      { id: "green-botanical-soft-sage", name: "Soft Sage", hex: "#D0E1D7", status: "Approved" },
      { id: "green-botanical-celadon", name: "Celadon", hex: "#C7DCCF", status: "Approved" },
      { id: "green-botanical-sage-mist", name: "Sage Mist", hex: "#BED8C8", status: "Approved" },
      { id: "green-botanical-eucalyptus", name: "Eucalyptus", hex: "#B5D3C1", status: "Approved" },
      { id: "green-botanical-sage", name: "Sage", hex: "#ABCFBA", status: "Approved" },
      { id: "green-botanical-botanical-grey", name: "Botanical Grey", hex: "#A2CBAB", status: "Core" },
      { id: "green-botanical-moss-milk", name: "Moss Milk", hex: "#98C7A3", status: "Approved" },
      { id: "green-botanical-laurel", name: "Laurel", hex: "#8EC39B", status: "Approved" },
      { id: "green-botanical-olive-sage", name: "Olive Sage", hex: "#84C092", status: "Approved" },
      { id: "green-botanical-muted-fern", name: "Muted Fern", hex: "#79BC8A", status: "Approved" },
      { id: "green-botanical-olive-moss", name: "Olive Moss", hex: "#6FB981", status: "Approved" },
      { id: "green-botanical-herb-green", name: "Herb Green", hex: "#64B679", status: "Approved" },
      { id: "green-botanical-fern-silk", name: "Fern Silk", hex: "#59B359", status: "Core" },
      { id: "green-botanical-botanical-green", name: "Botanical Green", hex: "#4EB04F", status: "Approved" },
      { id: "green-botanical-deep-olive", name: "Deep Olive", hex: "#49A949", status: "Approved" },
      { id: "green-botanical-basil", name: "Basil", hex: "#43A044", status: "Approved" },
      { id: "green-botanical-emerald-silk", name: "Emerald Silk", hex: "#3E983F", status: "Approved" },
      { id: "green-botanical-forest-green", name: "Forest Green", hex: "#389039", status: "Approved" },
      { id: "green-botanical-pine-green", name: "Pine Green", hex: "#338735", status: "Approved" },
      { id: "green-botanical-deep-fern", name: "Deep Fern", hex: "#417E2E", status: "Approved" },
      { id: "green-botanical-jade-shadow", name: "Jade Shadow", hex: "#3B752A", status: "Approved" },
      { id: "green-botanical-cypress", name: "Cypress", hex: "#356C25", status: "Core" },
      { id: "green-botanical-bottle-green", name: "Bottle Green", hex: "#306221", status: "Approved" },
      { id: "green-botanical-dark-pine", name: "Dark Pine", hex: "#2A591D", status: "Approved" },
      { id: "green-botanical-blackened-olive", name: "Blackened Olive", hex: "#254F19", status: "Approved" },
      { id: "green-botanical-night-forest", name: "Night Forest", hex: "#1F4515", status: "Caution" },
      { id: "green-botanical-deep-forest", name: "Deep Forest", hex: "#1A3B11", status: "Caution" },
    ],
  },
  {
    id: "blue-porcelain",
    name: "Blue & Porcelain",
    description: "Powder blue, mist, porcelain, denim, navy, midnight.",
    swatches: [
      { id: "blue-porcelain-powder-blue", name: "Powder Blue", hex: "#ECF0F3", status: "Caution" },
      { id: "blue-porcelain-porcelain-milk", name: "Porcelain Milk", hex: "#E4E9EE", status: "Caution" },
      { id: "blue-porcelain-blue-mist", name: "Blue Mist", hex: "#DAE2E9", status: "Caution" },
      { id: "blue-porcelain-dawn-blue", name: "Dawn Blue", hex: "#D1DBE4", status: "Approved" },
      { id: "blue-porcelain-pale-delft", name: "Pale Delft", hex: "#C8D4DF", status: "Approved" },
      { id: "blue-porcelain-mist-blue", name: "Mist Blue", hex: "#BECDDB", status: "Approved" },
      { id: "blue-porcelain-washed-blue", name: "Washed Blue", hex: "#B4C6D7", status: "Approved" },
      { id: "blue-porcelain-porcelain-blue", name: "Porcelain Blue", hex: "#AABFD3", status: "Approved" },
      { id: "blue-porcelain-soft-denim", name: "Soft Denim", hex: "#A0B4CF", status: "Core" },
      { id: "blue-porcelain-cloud-blue", name: "Cloud Blue", hex: "#95ADCC", status: "Approved" },
      { id: "blue-porcelain-heritage-blue", name: "Heritage Blue", hex: "#8AA5C8", status: "Approved" },
      { id: "blue-porcelain-ceramic-blue", name: "Ceramic Blue", hex: "#7F9DC5", status: "Approved" },
      { id: "blue-porcelain-dusty-blue", name: "Dusty Blue", hex: "#7495C2", status: "Approved" },
      { id: "blue-porcelain-slate-blue", name: "Slate Blue", hex: "#698DC0", status: "Approved" },
      { id: "blue-porcelain-blue-smoke", name: "Blue Smoke", hex: "#5D85BD", status: "Approved" },
      { id: "blue-porcelain-oxford-blue", name: "Oxford Blue", hex: "#5275BB", status: "Core" },
      { id: "blue-porcelain-deep-porcelain", name: "Deep Porcelain", hex: "#466CB8", status: "Approved" },
      { id: "blue-porcelain-denim-ink", name: "Denim Ink", hex: "#4065B0", status: "Approved" },
      { id: "blue-porcelain-royal-porcelain", name: "Royal Porcelain", hex: "#3B5EA7", status: "Approved" },
      { id: "blue-porcelain-navy-silk", name: "Navy Silk", hex: "#36589E", status: "Approved" },
      { id: "blue-porcelain-navy-ink", name: "Navy Ink", hex: "#315195", status: "Approved" },
      { id: "blue-porcelain-deep-navy", name: "Deep Navy", hex: "#2C4B8C", status: "Approved" },
      { id: "blue-porcelain-ink-blue", name: "Ink Blue", hex: "#273D83", status: "Approved" },
      { id: "blue-porcelain-midnight-blue", name: "Midnight Blue", hex: "#233779", status: "Approved" },
      { id: "blue-porcelain-sapphire-ink", name: "Sapphire Ink", hex: "#1F316F", status: "Core" },
      { id: "blue-porcelain-storm-navy", name: "Storm Navy", hex: "#1B2B65", status: "Approved" },
      { id: "blue-porcelain-deep-delft", name: "Deep Delft", hex: "#17265B", status: "Approved" },
      { id: "blue-porcelain-nocturne-blue", name: "Nocturne Blue", hex: "#132150", status: "Approved" },
      { id: "blue-porcelain-black-navy", name: "Black Navy", hex: "#101C45", status: "Caution" },
      { id: "blue-porcelain-midnight-ink", name: "Midnight Ink", hex: "#0D173B", status: "Caution" },
    ],
  },
  {
    id: "teal-aqua",
    name: "Teal & Aqua",
    description: "Duck egg, seafoam, aqua, turquoise, teal, peacock.",
    swatches: [
      { id: "teal-aqua-aqua-milk", name: "Aqua Milk", hex: "#EAF0F0", status: "Caution" },
      { id: "teal-aqua-pale-seafoam", name: "Pale Seafoam", hex: "#E1EBEB", status: "Caution" },
      { id: "teal-aqua-duck-egg-mist", name: "Duck Egg Mist", hex: "#D9E6E6", status: "Caution" },
      { id: "teal-aqua-soft-duck-egg", name: "Soft Duck Egg", hex: "#D0E1E2", status: "Approved" },
      { id: "teal-aqua-sea-glass", name: "Sea Glass", hex: "#C7DCDD", status: "Approved" },
      { id: "teal-aqua-duck-egg", name: "Duck Egg", hex: "#BED7D8", status: "Approved" },
      { id: "teal-aqua-aqua-stone", name: "Aqua Stone", hex: "#B5D2D4", status: "Approved" },
      { id: "teal-aqua-muted-aqua", name: "Muted Aqua", hex: "#ABCED0", status: "Approved" },
      { id: "teal-aqua-seafoam", name: "Seafoam", hex: "#A2CCCC", status: "Core" },
      { id: "teal-aqua-spa-teal", name: "Spa Teal", hex: "#98C9C8", status: "Approved" },
      { id: "teal-aqua-light-turquoise", name: "Light Turquoise", hex: "#8EC5C4", status: "Approved" },
      { id: "teal-aqua-blue-sage", name: "Blue Sage", hex: "#84C2C1", status: "Approved" },
      { id: "teal-aqua-aqua-silk", name: "Aqua Silk", hex: "#79BFBE", status: "Approved" },
      { id: "teal-aqua-jade-aqua", name: "Jade Aqua", hex: "#6FBCBB", status: "Approved" },
      { id: "teal-aqua-muted-turquoise", name: "Muted Turquoise", hex: "#64B9B9", status: "Approved" },
      { id: "teal-aqua-teal-mist", name: "Teal Mist", hex: "#59B6AF", status: "Core" },
      { id: "teal-aqua-soft-teal", name: "Soft Teal", hex: "#4EB4AC", status: "Approved" },
      { id: "teal-aqua-classic-teal", name: "Classic Teal", hex: "#47ADA5", status: "Approved" },
      { id: "teal-aqua-peacock-teal", name: "Peacock Teal", hex: "#42A59D", status: "Approved" },
      { id: "teal-aqua-deep-teal", name: "Deep Teal", hex: "#3C9D96", status: "Approved" },
      { id: "teal-aqua-petrol-teal", name: "Petrol Teal", hex: "#37948E", status: "Approved" },
      { id: "teal-aqua-lagoon-ink", name: "Lagoon Ink", hex: "#328C86", status: "Approved" },
      { id: "teal-aqua-ocean-teal", name: "Ocean Teal", hex: "#2D8376", status: "Approved" },
      { id: "teal-aqua-pine-teal", name: "Pine Teal", hex: "#297A6E", status: "Approved" },
      { id: "teal-aqua-dark-turquoise", name: "Dark Turquoise", hex: "#247166", status: "Core" },
      { id: "teal-aqua-deep-peacock", name: "Deep Peacock", hex: "#20685D", status: "Approved" },
      { id: "teal-aqua-ink-teal", name: "Ink Teal", hex: "#1C5E55", status: "Approved" },
      { id: "teal-aqua-blackened-teal", name: "Blackened Teal", hex: "#18544C", status: "Approved" },
      { id: "teal-aqua-night-lagoon", name: "Night Lagoon", hex: "#154B43", status: "Caution" },
      { id: "teal-aqua-teal-black", name: "Teal Black", hex: "#11403A", status: "Caution" },
    ],
  },
  {
    id: "purple-plum",
    name: "Purple & Plum",
    description: "Lilac, lavender grey, mauve, plum, aubergine, grape ink.",
    swatches: [
      { id: "purple-plum-lilac-milk", name: "Lilac Milk", hex: "#F1EDF2", status: "Caution" },
      { id: "purple-plum-pale-lavender", name: "Pale Lavender", hex: "#EBE4ED", status: "Caution" },
      { id: "purple-plum-lavender-mist", name: "Lavender Mist", hex: "#E4DCE8", status: "Caution" },
      { id: "purple-plum-lavender-grey", name: "Lavender Grey", hex: "#DED3E3", status: "Approved" },
      { id: "purple-plum-soft-lilac", name: "Soft Lilac", hex: "#D8CADE", status: "Approved" },
      { id: "purple-plum-orchid-smoke", name: "Orchid Smoke", hex: "#D3C1D9", status: "Approved" },
      { id: "purple-plum-mauve-fog", name: "Mauve Fog", hex: "#CDB7D5", status: "Approved" },
      { id: "purple-plum-dusty-violet", name: "Dusty Violet", hex: "#C7AED0", status: "Approved" },
      { id: "purple-plum-heather", name: "Heather", hex: "#C6A4CC", status: "Core" },
      { id: "purple-plum-muted-orchid", name: "Muted Orchid", hex: "#C29AC8", status: "Approved" },
      { id: "purple-plum-mauve-shadow", name: "Mauve Shadow", hex: "#BD90C4", status: "Approved" },
      { id: "purple-plum-soft-plum", name: "Soft Plum", hex: "#B886C1", status: "Approved" },
      { id: "purple-plum-violet-silk", name: "Violet Silk", hex: "#B47BBD", status: "Approved" },
      { id: "purple-plum-smoked-violet", name: "Smoked Violet", hex: "#B071BA", status: "Approved" },
      { id: "purple-plum-orchid-mauve", name: "Orchid Mauve", hex: "#AC66B7", status: "Approved" },
      { id: "purple-plum-plum-rose", name: "Plum Rose", hex: "#B45BB4", status: "Core" },
      { id: "purple-plum-classic-plum", name: "Classic Plum", hex: "#B150B1", status: "Approved" },
      { id: "purple-plum-royal-plum", name: "Royal Plum", hex: "#AA49A9", status: "Approved" },
      { id: "purple-plum-aubergine", name: "Aubergine", hex: "#A244A1", status: "Approved" },
      { id: "purple-plum-grape-ink", name: "Grape Ink", hex: "#993E98", status: "Approved" },
      { id: "purple-plum-deep-violet", name: "Deep Violet", hex: "#913990", status: "Approved" },
      { id: "purple-plum-damson-plum", name: "Damson Plum", hex: "#883487", status: "Approved" },
      { id: "purple-plum-dark-orchid", name: "Dark Orchid", hex: "#7F2F70", status: "Approved" },
      { id: "purple-plum-fig-purple", name: "Fig Purple", hex: "#762A68", status: "Approved" },
      { id: "purple-plum-black-plum", name: "Black Plum", hex: "#6C255F", status: "Core" },
      { id: "purple-plum-night-violet", name: "Night Violet", hex: "#632156", status: "Approved" },
      { id: "purple-plum-deep-aubergine", name: "Deep Aubergine", hex: "#591D4E", status: "Approved" },
      { id: "purple-plum-black-grape", name: "Black Grape", hex: "#501945", status: "Approved" },
      { id: "purple-plum-ink-plum", name: "Ink Plum", hex: "#45153C", status: "Caution" },
      { id: "purple-plum-purple-black", name: "Purple Black", hex: "#3B1133", status: "Caution" },
    ],
  },
  {
    id: "brown-earth",
    name: "Brown & Earth",
    description: "Almond, camel, taupe, clay brown, cocoa, espresso.",
    swatches: [
      { id: "brown-earth-oat-milk", name: "Oat Milk", hex: "#F0EDEA", status: "Caution" },
      { id: "brown-earth-pale-almond", name: "Pale Almond", hex: "#EBE7E2", status: "Caution" },
      { id: "brown-earth-almond", name: "Almond", hex: "#E6E0D9", status: "Caution" },
      { id: "brown-earth-soft-sand", name: "Soft Sand", hex: "#E0D9D0", status: "Approved" },
      { id: "brown-earth-light-camel", name: "Light Camel", hex: "#DBD2C7", status: "Approved" },
      { id: "brown-earth-warm-taupe", name: "Warm Taupe", hex: "#D7CCBE", status: "Approved" },
      { id: "brown-earth-biscuit", name: "Biscuit", hex: "#D2C5B5", status: "Approved" },
      { id: "brown-earth-camel", name: "Camel", hex: "#CDBEAC", status: "Approved" },
      { id: "brown-earth-mocha-milk", name: "Mocha Milk", hex: "#C9B4A2", status: "Core" },
      { id: "brown-earth-soft-mocha", name: "Soft Mocha", hex: "#C5AD98", status: "Approved" },
      { id: "brown-earth-latte", name: "Latte", hex: "#C1A58F", status: "Approved" },
      { id: "brown-earth-clay-beige", name: "Clay Beige", hex: "#BD9E85", status: "Approved" },
      { id: "brown-earth-tan", name: "Tan", hex: "#B9977A", status: "Approved" },
      { id: "brown-earth-toffee", name: "Toffee", hex: "#B69070", status: "Approved" },
      { id: "brown-earth-caramel-brown", name: "Caramel Brown", hex: "#B28966", status: "Approved" },
      { id: "brown-earth-clay-brown", name: "Clay Brown", hex: "#AF7D5B", status: "Core" },
      { id: "brown-earth-cinnamon-taupe", name: "Cinnamon Taupe", hex: "#AB7551", status: "Approved" },
      { id: "brown-earth-warm-brown", name: "Warm Brown", hex: "#A36F4C", status: "Approved" },
      { id: "brown-earth-cocoa", name: "Cocoa", hex: "#9A6846", status: "Approved" },
      { id: "brown-earth-walnut", name: "Walnut", hex: "#926240", status: "Approved" },
      { id: "brown-earth-chestnut", name: "Chestnut", hex: "#895B3B", status: "Approved" },
      { id: "brown-earth-coffee", name: "Coffee", hex: "#815536", status: "Approved" },
      { id: "brown-earth-espresso", name: "Espresso", hex: "#784A31", status: "Approved" },
      { id: "brown-earth-dark-cocoa", name: "Dark Cocoa", hex: "#6F442C", status: "Approved" },
      { id: "brown-earth-burnt-umber", name: "Burnt Umber", hex: "#663D27", status: "Core" },
      { id: "brown-earth-mahogany-brown", name: "Mahogany Brown", hex: "#5C3723", status: "Approved" },
      { id: "brown-earth-deep-walnut", name: "Deep Walnut", hex: "#53311E", status: "Approved" },
      { id: "brown-earth-black-coffee", name: "Black Coffee", hex: "#492B1A", status: "Approved" },
      { id: "brown-earth-earth-black", name: "Earth Black", hex: "#3F2516", status: "Caution" },
      { id: "brown-earth-brown-black", name: "Brown Black", hex: "#361F12", status: "Caution" },
    ],
  },
  {
    id: "ivory-beige",
    name: "Ivory & Beige",
    description: "Ivory, pearl, cream, linen, sand, beige, deeper warm bases.",
    swatches: [
      { id: "ivory-beige-snow", name: "Snow", hex: "#FAFAF9", status: "Caution" },
      { id: "ivory-beige-ivory-pearl", name: "Ivory Pearl", hex: "#F6F5F4", status: "Caution" },
      { id: "ivory-beige-ivory", name: "Ivory", hex: "#F1F0EE", status: "Caution" },
      { id: "ivory-beige-warm-ivory", name: "Warm Ivory", hex: "#EDEBE8", status: "Approved" },
      { id: "ivory-beige-cream", name: "Cream", hex: "#E9E7E2", status: "Approved" },
      { id: "ivory-beige-vanilla-cream", name: "Vanilla Cream", hex: "#E5E2DB", status: "Approved" },
      { id: "ivory-beige-linen", name: "Linen", hex: "#E0DDD5", status: "Approved" },
      { id: "ivory-beige-soft-canvas", name: "Soft Canvas", hex: "#DCD9CF", status: "Approved" },
      { id: "ivory-beige-porcelain-beige", name: "Porcelain Beige", hex: "#D9D3C8", status: "Core" },
      { id: "ivory-beige-oat", name: "Oat", hex: "#D5CEC2", status: "Approved" },
      { id: "ivory-beige-natural-cotton", name: "Natural Cotton", hex: "#D1C9BB", status: "Approved" },
      { id: "ivory-beige-parchment", name: "Parchment", hex: "#CDC5B4", status: "Approved" },
      { id: "ivory-beige-almond-cream", name: "Almond Cream", hex: "#CAC0AE", status: "Approved" },
      { id: "ivory-beige-warm-linen", name: "Warm Linen", hex: "#C6BCA7", status: "Approved" },
      { id: "ivory-beige-sand", name: "Sand", hex: "#C3B7A0", status: "Approved" },
      { id: "ivory-beige-beige-silk", name: "Beige Silk", hex: "#C0B098", status: "Core" },
      { id: "ivory-beige-soft-khaki", name: "Soft Khaki", hex: "#BDAB91", status: "Approved" },
      { id: "ivory-beige-warm-beige", name: "Warm Beige", hex: "#B9A78A", status: "Approved" },
      { id: "ivory-beige-honey-beige", name: "Honey Beige", hex: "#B6A283", status: "Approved" },
      { id: "ivory-beige-tea-beige", name: "Tea Beige", hex: "#B39E7B", status: "Approved" },
      { id: "ivory-beige-stone-beige", name: "Stone Beige", hex: "#B19974", status: "Approved" },
      { id: "ivory-beige-muted-sand", name: "Muted Sand", hex: "#AE956C", status: "Approved" },
      { id: "ivory-beige-deep-linen", name: "Deep Linen", hex: "#AB8B64", status: "Approved" },
      { id: "ivory-beige-fawn-beige", name: "Fawn Beige", hex: "#A9875C", status: "Approved" },
      { id: "ivory-beige-dark-beige", name: "Dark Beige", hex: "#A58256", status: "Core" },
      { id: "ivory-beige-warm-greige", name: "Warm Greige", hex: "#9F7D51", status: "Approved" },
      { id: "ivory-beige-khaki-beige", name: "Khaki Beige", hex: "#99784D", status: "Approved" },
      { id: "ivory-beige-dune", name: "Dune", hex: "#937248", status: "Approved" },
      { id: "ivory-beige-deep-sand", name: "Deep Sand", hex: "#8D6D44", status: "Caution" },
      { id: "ivory-beige-aged-beige", name: "Aged Beige", hex: "#876840", status: "Caution" },
    ],
  },
  {
    id: "grey-ink",
    name: "Grey & Ink",
    description: "Pearl grey, warm grey, stone, charcoal, soft black, ink.",
    swatches: [
      { id: "grey-ink-pearl-grey", name: "Pearl Grey", hex: "#F3F2F2", status: "Caution" },
      { id: "grey-ink-cloud-grey", name: "Cloud Grey", hex: "#EBEBEA", status: "Caution" },
      { id: "grey-ink-soft-grey", name: "Soft Grey", hex: "#E4E3E1", status: "Caution" },
      { id: "grey-ink-warm-grey", name: "Warm Grey", hex: "#DDDBD9", status: "Approved" },
      { id: "grey-ink-silver-stone", name: "Silver Stone", hex: "#D5D3D1", status: "Approved" },
      { id: "grey-ink-mushroom-grey", name: "Mushroom Grey", hex: "#CECBC8", status: "Approved" },
      { id: "grey-ink-dove-grey", name: "Dove Grey", hex: "#C7C4C0", status: "Approved" },
      { id: "grey-ink-stone", name: "Stone", hex: "#C0BCB7", status: "Approved" },
      { id: "grey-ink-ash-beige", name: "Ash Beige", hex: "#B9B2AE", status: "Core" },
      { id: "grey-ink-greige", name: "Greige", hex: "#B2AAA6", status: "Approved" },
      { id: "grey-ink-smoked-pearl", name: "Smoked Pearl", hex: "#ABA29D", status: "Approved" },
      { id: "grey-ink-taupe-grey", name: "Taupe Grey", hex: "#A49994", status: "Approved" },
      { id: "grey-ink-slate-warm", name: "Slate Warm", hex: "#9D918C", status: "Approved" },
      { id: "grey-ink-medium-grey", name: "Medium Grey", hex: "#968983", status: "Approved" },
      { id: "grey-ink-graphite-soft", name: "Graphite Soft", hex: "#90817A", status: "Approved" },
      { id: "grey-ink-ink-grey", name: "Ink Grey", hex: "#717988", status: "Core" },
      { id: "grey-ink-charcoal", name: "Charcoal", hex: "#6A7180", status: "Approved" },
      { id: "grey-ink-warm-charcoal", name: "Warm Charcoal", hex: "#626978", status: "Approved" },
      { id: "grey-ink-deep-graphite", name: "Deep Graphite", hex: "#5B6270", status: "Approved" },
      { id: "grey-ink-ink-brown", name: "Ink Brown", hex: "#545A67", status: "Approved" },
      { id: "grey-ink-soft-black", name: "Soft Black", hex: "#4C525F", status: "Approved" },
      { id: "grey-ink-washed-black", name: "Washed Black", hex: "#454B57", status: "Approved" },
      { id: "grey-ink-carbon", name: "Carbon", hex: "#3E3E4E", status: "Approved" },
      { id: "grey-ink-deep-ink", name: "Deep Ink", hex: "#373746", status: "Approved" },
      { id: "grey-ink-blackened-brown", name: "Blackened Brown", hex: "#30303D", status: "Core" },
      { id: "grey-ink-almost-black", name: "Almost Black", hex: "#292934", status: "Approved" },
      { id: "grey-ink-ink-black", name: "Ink Black", hex: "#22222C", status: "Approved" },
      { id: "grey-ink-noir", name: "Noir", hex: "#1B1B23", status: "Approved" },
      { id: "grey-ink-textile-black", name: "Textile Black", hex: "#14141A", status: "Caution" },
      { id: "grey-ink-absolute-ink", name: "Absolute Ink", hex: "#0D0D11", status: "Caution" },
    ],
  },
  {
    id: "metallic-special-finish",
    name: "Metallic & Special Finish",
    description: "Screen previews for premium finish, shimmer, pearl, bronze, gold, silver.",
    swatches: [
      { id: "metallic-special-finish-pearl-sheen", name: "Pearl Sheen", hex: "#F7F6F3", status: "Caution" },
      { id: "metallic-special-finish-soft-pearl", name: "Soft Pearl", hex: "#F1F0EB", status: "Caution" },
      { id: "metallic-special-finish-champagne", name: "Champagne", hex: "#ECEAE3", status: "Caution" },
      { id: "metallic-special-finish-pale-gold", name: "Pale Gold", hex: "#E8E5DB", status: "Premium" },
      { id: "metallic-special-finish-metallic", name: "Metallic", hex: "#E3DFD3", status: "Approved" },
      { id: "metallic-special-finish-light-gold", name: "Light Gold", hex: "#DEDACA", status: "Approved" },
      { id: "metallic-special-finish-silk-gold", name: "Silk Gold", hex: "#DAD5C1", status: "Approved" },
      { id: "metallic-special-finish-champagne-gold", name: "Champagne Gold", hex: "#D6D0B8", status: "Premium" },
      { id: "metallic-special-finish-antique-gold", name: "Antique Gold", hex: "#D2C7AF", status: "Approved" },
      { id: "metallic-special-finish-bright-brass", name: "Bright Brass", hex: "#CFC2A6", status: "Approved" },
      { id: "metallic-special-finish-muted-brass", name: "Muted Brass", hex: "#CBBD9C", status: "Approved" },
      { id: "metallic-special-finish-old-gold", name: "Old Gold", hex: "#C8B793", status: "Approved" },
      { id: "metallic-special-finish-metallic-bronze", name: "Metallic Bronze", hex: "#C5B289", status: "Approved" },
      { id: "metallic-special-finish-light-rose-gold", name: "Light Rose Gold", hex: "#C2AD7F", status: "Premium" },
      { id: "metallic-special-finish-rose-gold", name: "Rose Gold", hex: "#BFA875", status: "Approved" },
      { id: "metallic-special-finish-warm-bronze", name: "Warm Bronze", hex: "#BC966A", status: "Core" },
      { id: "metallic-special-finish-aged-bronze", name: "Aged Bronze", hex: "#BA9060", status: "Approved" },
      { id: "metallic-special-finish-bronze-metallic", name: "Bronze Metallic", hex: "#B88A55", status: "Premium" },
      { id: "metallic-special-finish-pewter-light", name: "Pewter Light", hex: "#B6844A", status: "Approved" },
      { id: "metallic-special-finish-soft-silver", name: "Soft Silver", hex: "#AE7E44", status: "Approved" },
      { id: "metallic-special-finish-metallic-silver", name: "Metallic Silver", hex: "#A6773F", status: "Approved" },
      { id: "metallic-special-finish-smoke-pewter", name: "Smoke Pewter", hex: "#9F713A", status: "Approved" },
      { id: "metallic-special-finish-gunmetal-soft", name: "Gunmetal Soft", hex: "#965735", status: "Approved" },
      { id: "metallic-special-finish-dark-pewter", name: "Dark Pewter", hex: "#8E5130", status: "Premium" },
      { id: "metallic-special-finish-antique-bronze", name: "Antique Bronze", hex: "#864C2C", status: "Core" },
      { id: "metallic-special-finish-smoked-gold", name: "Smoked Gold", hex: "#7D4627", status: "Approved" },
      { id: "metallic-special-finish-deep-bronze", name: "Deep Bronze", hex: "#744023", status: "Approved" },
      { id: "metallic-special-finish-dark-gunmetal", name: "Dark Gunmetal", hex: "#6B3B1F", status: "Premium" },
      { id: "metallic-special-finish-blackened-bronze", name: "Blackened Bronze", hex: "#62351B", status: "Caution" },
      { id: "metallic-special-finish-metallic-ink", name: "Metallic Ink", hex: "#592F18", status: "Caution" },
    ],
  },
];

/* ── Helper utilities ───────────────────────────────────────────────────── */

/** Flat list of all 360 swatches */
export const ALL_SWATCHES: NahkyaSwatch[] = NAHKYA_SWATCH_CATEGORIES.flatMap(
  (c) => c.swatches
);

/** Lookup swatch by exact hex (case-insensitive) */
export function findSwatchByHex(hex: string): NahkyaSwatch | undefined {
  const normalised = hex.toLowerCase();
  return ALL_SWATCHES.find((s) => s.hex.toLowerCase() === normalised);
}

/** Lookup swatch by name (case-insensitive, partial match) */
export function findSwatchesByName(query: string): NahkyaSwatch[] {
  const q = query.toLowerCase();
  return ALL_SWATCHES.filter((s) => s.name.toLowerCase().includes(q));
}

/** Get swatches filtered by status */
export function getSwatchesByStatus(status: SwatchStatus): NahkyaSwatch[] {
  return ALL_SWATCHES.filter((s) => s.status === status);
}

/** Count by status */
export function getSwatchStatusCounts(): Record<SwatchStatus, number> {
  return ALL_SWATCHES.reduce(
    (acc, s) => {
      acc[s.status] = (acc[s.status] || 0) + 1;
      return acc;
    },
    { Caution: 0, Approved: 0, Core: 0, Premium: 0 } as Record<SwatchStatus, number>
  );
}

/** Category names for UI dropdowns */
export const SWATCH_CATEGORY_OPTIONS = NAHKYA_SWATCH_CATEGORIES.map((c) => ({
  value: c.id,
  label: c.name,
}));
