/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        /* ── v10 Soft Burgundy + Gold tokens ── */
        nahkya: {
          bg: 'var(--nahkya-bg)',
          surface: 'var(--nahkya-surface)',
          'surface-soft': 'var(--nahkya-surface-soft)',
          'surface-warm': 'var(--nahkya-surface-warm)',
          text: 'var(--nahkya-text)',
          'text-strong': 'var(--nahkya-text-strong)',
          'text-muted': 'var(--nahkya-text-muted)',
          'text-soft': 'var(--nahkya-text-soft)',
          'text-inverse': 'var(--nahkya-text-inverse)',
          burgundy: 'var(--nahkya-burgundy)',
          'burgundy-dark': 'var(--nahkya-burgundy-dark)',
          'burgundy-soft': 'var(--nahkya-burgundy-soft)',
          gold: 'var(--nahkya-gold)',
          'gold-soft': 'var(--nahkya-gold-soft)',
          'gold-muted': 'var(--nahkya-gold-muted)',
          'gold-veil': 'var(--nahkya-gold-veil)',
          border: 'var(--nahkya-border)',
          'border-strong': 'var(--nahkya-border-strong)',
          error: 'var(--nahkya-error)',
          'error-soft': 'var(--nahkya-error-soft)',
          success: 'var(--nahkya-success)',
          'success-soft': 'var(--nahkya-success-soft)',
          /* Legacy mappings — kept for backward compatibility during migration */
          ivory: 'var(--nahkya-ivory)',
          cream: 'var(--nahkya-cream)',
          stone: 'var(--nahkya-stone)',
          taupe: 'var(--nahkya-taupe)',
          sand: 'var(--nahkya-sand)',
          charcoal: 'var(--nahkya-charcoal)',
          'soft-black': 'var(--nahkya-soft-black)',
          'gold-light': 'var(--nahkya-gold-light)',
          'text-secondary': 'var(--nahkya-text-secondary)',
          rose: 'var(--nahkya-rose)',
          teal: 'var(--nahkya-teal)',
          fuchsia: 'var(--nahkya-fuchsia)',
        },
        workspace: {
          bg: 'var(--workspace-bg)',
          sidebar: 'var(--workspace-sidebar)',
          panel: 'var(--workspace-panel)',
          border: 'var(--workspace-border)',
          hover: 'var(--workspace-hover)',
        },
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'monospace'],
      },
      fontSize: {
        'display-xxl': ['96px', { lineHeight: '0.95', letterSpacing: '-0.03em' }],
        'display-xl': ['72px', { lineHeight: '0.98', letterSpacing: '-0.02em' }],
        'display-lg': ['56px', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        'display-md': ['40px', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
        'display-sm': ['32px', { lineHeight: '1.15', letterSpacing: '-0.01em' }],
        'display-xs': ['52px', { lineHeight: '1.0', letterSpacing: '-0.02em' }],
        'display-xxxl': ['120px', { lineHeight: '0.9', letterSpacing: '-0.03em' }],
        'display-mega': ['200px', { lineHeight: '0.85', letterSpacing: '-0.03em' }],
        'heading-lg': ['24px', { lineHeight: '1.3' }],
        'heading-md': ['20px', { lineHeight: '1.35' }],
        'heading-sm': ['28px', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'body-lg': ['17px', { lineHeight: '1.5' }],
        'body-md': ['15px', { lineHeight: '1.5' }],
        'body-sm': ['13px', { lineHeight: '1.5' }],
        'body-xs': ['12px', { lineHeight: '1.5' }],
        'body-2xs': ['11px', { lineHeight: '1.5' }],
        'body-3xs': ['10px', { lineHeight: '1.4' }],
        'mono-lg': ['13px', { lineHeight: '1.4', letterSpacing: '0.08em' }],
        'mono-md': ['12px', { lineHeight: '1.4', letterSpacing: '0.1em' }],
        'mono-sm': ['10px', { lineHeight: '1.4', letterSpacing: '0.12em' }],
      },
      spacing: {
        'sidebar-member': '240px',
        'sidebar-member-collapsed': '80px',
        'sidebar-admin': '260px',
        'panel-studio': '280px',
        'panel-inspector': '330px',
        'panel-preview': '380px',
        'button-sm': '36px',
        'button': '44px',
        'button-lg': '52px',
        'nav': '72px',
        'toolbar': '74px',
      },
      maxWidth: {
        'container': '1520px',
        'auth': '420px',
        'auth-lg': '440px',
        'canvas': '500px',
        'stage-source': '640px',
        'stage-preview': '520px',
        'prose': '560px',
        'content': '600px',
        'content-lg': '640px',
        'tablet': '760px',
        'editor': '1120px',
      },
      gridTemplateColumns: {
        'admin-preview': '1fr 380px',
        'colour-row': '1fr 120px 200px',
      },
      maxHeight: {
        'canvas': '500px',
        '90vh': '90vh',
      },
      aspectRatio: {
        '4/5': '4 / 5',
        '16/10': '16 / 10',
        '2/1': '2 / 1',
        '4/3': '4 / 3',
        '3/4': '3 / 4',
      },
      minHeight: {
        'image': '180px',
        'hero': '370px',
      },
      borderRadius: {
        nahkya: 'var(--radius-nahkya)',
        'nahkya-sm': 'var(--radius-nahkya-sm)',
        'nahkya-md': 'var(--radius-nahkya-md)',
        'nahkya-lg': 'var(--radius-nahkya-lg)',
        'nahkya-xl': 'var(--radius-nahkya-xl)',
        'nahkya-pill': 'var(--radius-pill)',
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        '4xl': '2rem',
      },
      zIndex: {
        'behind': '-10',
        'content': '10',
        'dropdown': '20',
        'toolbar': '30',
        'nav': '50',
        'modal': '60',
        'toast': '80',
        'loading': '100',
      },
      boxShadow: {
        'gold-focus': '0 0 0 3px rgba(184, 139, 74, 0.25)',
        'gold-glow': '0 0 12px rgba(184, 139, 74, 0.65)',
        'gold-glow-soft': '0 0 12px rgba(184, 139, 74, 0.45)',
        'soft': 'var(--shadow-soft)',
        'card': 'var(--shadow-card)',
        'burgundy': 'var(--shadow-burgundy)',
        'focus-ring': 'var(--focus-ring)',
      },
      letterSpacing: {
        'label': '0.08em',
        'widest-alt': '0.15em',
        'hero': '0.2em',
        'hero-wide': '0.3em',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "scroll-bounce": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(16px)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "1" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "shimmer": "shimmer 1.5s ease-in-out infinite",
        "scroll-bounce": "scroll-bounce 2s ease-in-out infinite",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        "spin-slow": "spin-slow 2s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
