/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      screens: {
        xs: '320px',
        phone: '480px',
        wide: '1536px',
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        /* ── Nahkya Semantic Tokens ── */
        nahkya: {
          bg: 'var(--nahkya-bg)',
          surface: 'var(--nahkya-surface)',
          'surface-raised': 'var(--nahkya-surface-raised)',
          text: 'var(--nahkya-text)',
          'text-secondary': 'var(--nahkya-text-secondary)',
          inverse: 'var(--nahkya-inverse)',
          accent: 'var(--nahkya-accent)',
          'accent-hover': 'var(--nahkya-accent-hover)',
          'accent-active': 'var(--nahkya-accent-active)',
          'accent-subtle': 'var(--nahkya-accent-subtle)',
          highlight: 'var(--nahkya-highlight)',
          'highlight-hover': 'var(--nahkya-highlight-hover)',
          'highlight-subtle': 'var(--nahkya-highlight-subtle)',
          border: 'var(--nahkya-border)',
          error: 'var(--nahkya-error)',
          'error-subtle': 'var(--nahkya-error-subtle)',
          success: 'var(--nahkya-success)',
          'success-subtle': 'var(--nahkya-success-subtle)',
          warning: 'var(--nahkya-warning)',
          'warning-subtle': 'var(--nahkya-warning-subtle)',
          info: 'var(--nahkya-info)',
          'info-subtle': 'var(--nahkya-info-subtle)',
          olive: 'var(--nahkya-olive)',
          'olive-subtle': 'var(--nahkya-olive-subtle)',
          muted: 'var(--nahkya-muted)',
          disabled: 'var(--nahkya-disabled)',
          'disabled-text': 'var(--nahkya-disabled-text)',
        },
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['Inter', '-apple-system', 'system-ui', 'sans-serif'],
        mono: ['"Fira Code"', 'monospace'],
      },
      fontSize: {
        'display-xl': ['clamp(2.25rem, 1.5rem + 4vw, 6rem)', { lineHeight: '0.98', letterSpacing: '-0.02em' }],
        'display-lg': ['clamp(2rem, 1.4rem + 3vw, 4.5rem)', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        'display-md': ['clamp(1.75rem, 1.3rem + 2.25vw, 3.5rem)', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
        'display-sm': ['clamp(1.5rem, 1.2rem + 1.5vw, 2.5rem)', { lineHeight: '1.15', letterSpacing: '-0.01em' }],
        'heading-lg': ['clamp(1.375rem, 1.1rem + 1.38vw, 2.5rem)', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'heading-md': ['clamp(1.125rem, 1rem + 0.5vw, 1.5rem)', { lineHeight: '1.35' }],
        'heading-sm': ['clamp(1rem, 0.95rem + 0.25vw, 1.25rem)', { lineHeight: '1.3' }],
        'body-lg': ['clamp(1.0625rem, 0.95rem + 0.5vw, 1.25rem)', { lineHeight: '1.6' }],
        'body-md': ['1rem', { lineHeight: '1.6' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5' }],
        'body-xs': ['0.75rem', { lineHeight: '1.5' }],
        'body-2xs': ['0.6875rem', { lineHeight: '1.5' }],
        'body-3xs': ['0.625rem', { lineHeight: '1.4' }],
        'mono-lg': ['0.8125rem', { lineHeight: '1.4', letterSpacing: '0.08em' }],
        'mono-md': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.1em' }],
        'mono-sm': ['0.625rem', { lineHeight: '1.4', letterSpacing: '0.12em' }],
      },
      spacing: {
        'sidebar-member': '240px',
        'sidebar-member-collapsed': '80px',
        'sidebar-admin': '260px',
        'sidebar-expanded': '280px',
        'sidebar-collapsed': '64px',
        'panel-studio': '280px',
        'panel-inspector': '330px',
        'panel-preview': '380px',
        'button-sm': '36px',
        'button': '44px',
        'button-lg': '52px',
        'nav': '72px',
        'toolbar': '74px',
        '50': '12.5rem',
      },
      maxWidth: {
        'preview': '960px',
        'container': '1520px',
        'auth': '420px',
        'auth-lg': '440px',
        'canvas': '500px',
        'stage-source': '640px',
        'stage-preview': '520px',
        'prose': '560px',
        'content': '600px',
        'content-lg': '640px',
        'tablet': '760px',
        'editor': '1120px',
      },
      gridTemplateColumns: {
        'admin-preview': '1fr 380px',
        'colour-row': '1fr 120px 200px',
      },
      maxHeight: {
        'canvas': '500px',
        '80vh': '80vh',
        '90vh': '90vh',
      },
      aspectRatio: {
        '4/5': '4 / 5',
        '16/10': '16 / 10',
        '2/1': '2 / 1',
        '4/3': '4 / 3',
        '3/4': '3 / 4',
      },
      minHeight: {
        'image': '180px',
        'hero': '370px',
        'hero-section': '80vh',
      },
      borderRadius: {
        nahkya: 'var(--radius-nahkya)',
        'nahkya-sm': 'var(--radius-nahkya-sm)',
        'nahkya-md': 'var(--radius-nahkya-md)',
        'nahkya-lg': 'var(--radius-nahkya-lg)',
        'nahkya-xl': 'var(--radius-nahkya-xl)',
        'nahkya-pill': 'var(--radius-pill)',
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        '4xl': '2rem',
      },
      zIndex: {
        'behind': '-10',
        'content': '10',
        'dropdown': '20',
        'toolbar': '30',
        'nav': '50',
        'modal': '60',
        'toast': '80',
        'loading': '100',
      },
      boxShadow: {
        'gold-focus': '0 0 0 3px rgba(200, 164, 100, 0.3)',
        'gold-glow': '0 0 12px rgba(200, 164, 100, 0.65)',
        'gold-glow-soft': '0 0 12px rgba(200, 164, 100, 0.45)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        'soft': 'var(--shadow-soft)',
        'card': 'var(--shadow-card)',
        'burgundy': 'var(--shadow-burgundy)',
        'focus-ring': 'var(--shadow-focus)',
        'editor': 'var(--shadow-editor)',
      },
      letterSpacing: {
        'label': '0.08em',
        'widest-alt': '0.15em',
        'hero': '0.2em',
        'hero-wide': '0.3em',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "scroll-bounce": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(16px)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "1" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "shimmer": "shimmer 1.5s ease-in-out infinite",
        "scroll-bounce": "scroll-bounce 2s ease-in-out infinite",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        "spin-slow": "spin-slow 2s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/container-queries")],
}
